name: Preview Build

on: [push]

jobs:
  build-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Build Script
        run: |
          npm run build

      - run: |
          zip -r dist.zip dist

      - name: Upload dist artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist.zip
          retention-days: 5
