name: Build and Deploy
on:
  push:
    branches:
      - master # 可以根据你的主分支名称进行修改

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-project-artifact
          path: path/to/built/files

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-project-artifact
          path: path/to/download/artifact


